### Teste de conexão com o banco
GET http://localhost:3000/test-db

### Cadastro de usuário
POST http://localhost:3000/cadastro
Content-Type: application/json

{
  "nome": "Teste",
  "email": "teste@teste.com",
  "senha": "123456"
}
### Login de usuário
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "descartavel@teste.com",
  "senha": "123456"
}
### Perfil - sem token 
GET http://localhost:3000/perfil

### Perfil - com token válido 
GET http://localhost:3000/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0ZUB0ZXN0ZS5jb20iLCJpYXQiOjE3OTAwODkyNzQsImV4cCI6MTc5MDA5NjQ3NH0.nR1Ci6Pl3_9wzJKZN9ckcaC7IMAxKq8l__B6d6ukaE4

### Perfil - com token inválido 
GET http://localhost:3000/perfil
Authorization: Bearer token_falso_qualquer

### Ver logs (protegida - precisa de token)
GET http://localhost:3000/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0ZUB0ZXN0ZS5jb20iLCJpYXQiOjE3OTAzNTUxMjksImV4cCI6MTc5MDM2MjMyOX0.0Umc-FZfXTeYhm5fuf6l07lJDcBaRQFeWglei1YiYeg

### Cadastro SEM aceitar termos 
POST http://localhost:3000/cadastro
Content-Type: application/json

{
  "nome": "Teste Sem Termos",
  "email": "semtermos@teste.com",
  "senha": "123456"
}

### Cadastro COM aceite dos termos 
POST http://localhost:3000/cadastro
Content-Type: application/json

{
  "nome": "Teste Com Termos",
  "email": "descartavel@teste.com",
  "senha": "123456",
  "aceitouTermos": true
}
### Buscar Termos de Uso (público)
GET http://localhost:3000/termos

### Buscar Política de Privacidade (público)
GET http://localhost:3000/politica
### Excluir minha conta - sem token (deve dar erro 401)
DELETE http://localhost:3000/minha-conta

### Excluir minha conta - com token (deve funcionar)
DELETE http://localhost:3000/minha-conta
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImVtYWlsIjoiZGVzY2FydGF2ZWxAdGVzdGUuY29tIiwiaWF0IjoxNzkwNTE0MzA4LCJleHAiOjE3OTA1MjE1MDh9.FyqIqdyLnpFU1pL35uUoeqjlBfr9-vxlWD1O22Jcfbk